import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Feed from "@/components/ Feed";
import { getImages } from "@/components/ Feed/getImages";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <div style={{ marginTop: "450px" }}></div>

        <Feed title="Continuar assistindo como Nany" imagesSrc={getImages(1)}  />
        <Feed title="Séries de comédia romântica" imagesSrc={getImages(2)}  />
        <Feed title="Filmes alto-astral" imagesSrc={getImages(3)}  />
        <Feed title="Lançamentos" imagesSrc={getImages(4)}  />
        <Feed title="Minha lista" imagesSrc={getImages(5)}  />
        <Feed title="Assitir novamente" imagesSrc={getImages(6)} />
      </main>
    </>
  );
}
