import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Feed from "@/components/ Feed";
import { getThumbnails } from "@/components/ Feed/utils/getThumbnails";
import Highlight from "@/components/Highlight";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <Highlight />

        <Feed title="Continuar assistindo como Nany" thumbnails={getThumbnails("continue-watching")}  />
        <Feed title="Séries de comédia romântica" thumbnails={getThumbnails("romantic-comedy")}  />
        <Feed title="Filmes alto-astral" thumbnails={getThumbnails("high-spirits")}  />
        <Feed title="Lançamentos" thumbnails={getThumbnails("releases")}  />
        <Feed title="Minha lista" thumbnails={getThumbnails("my-list")}  />
        <Feed title="Assitir novamente" thumbnails={getThumbnails("watch-again")} />
      </main>
    </>
  );
}
